server:
  port: 3366
spring:
  application:
    name: rookie-config-order-consumer
  #spring-cloud-config最新版本的建议配置
  config:
    import: "optional:configserver:http://localhost:3344"
  cloud:
    #Config客户端配置
    config:
      label: main #分支名称
      name: config #配置文件名称
      profile: dev #读取后缀名称   上述3个综合：master分支上config-dev.yml的配置文件被读取http://localhost:3344/main/config-dev.yml
#      uri: http://localhost:3344 #配置中心地址k
  #RabbitMQ相关支持
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    stream:
      username: guest
      password: guest

eureka:
  instance:
    instance-id: rookie-order-consumer
  #  instance:
#    prefer-ip-address: true
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      defaultZone: http://eureka-server.dev.com:8761/eureka
      #defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server.dev.com:8761/eureka}
      # 集群版
      #defaultZone: http://eureka.server8761.com:8761/eureka/,http://eureka.server8762.com:8762/eureka/,http://eureka.server8763.com:8763/eureka/

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"