server:
  port: 9091 #指定运行端口
spring:
  application:
    name: eureka-producer #指定服务名称
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server.dev.com:8761/eureka}


logging:
  level:
    root: info